#!/usr/bin/env bash
# Raw PATH
export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"

# Add '$HOME/bin' to the $PATH
export PATH="$HOME/bin:$PATH"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# AWS paths
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:/usr/local/phabricator/arcanist/bin"

# Ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/lib/ruby/gems/2.7.0/bin:$PATH"

# GO
export GOROOT="/usr/local/go"       # GOROOT is the location where Go package is installed on your system.
export GOPATH="$HOME/repos/go"      # GOPATH is the location of your work directory
export PATH="$PATH:/usr/local/opt/go/libexec/bin"
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# MacTex
export PATH="$PATH:/usr/local/texlive/2019/bin/x86_64-darwin"

# openssl
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
